version: '3.8'

services:
  # === API ===
  # api:
  #   build: 
        # context: .
        # dockerfile: Dockerfile.app
  #   container_name: kg_api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/kg_mvp
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=password
  #     - QDRANT_HOST=qdrant
  #     - QDRANT_PORT=6333
  #     - REDIS_URL=redis://redis:6379/0
  #     - UPLOAD_DIR=/app/uploads/raw
  #     - OPENAI_API_KEY=${OPENAI_API_KEY:-}
  #   volumes:
  #     - ./uploads:/app/uploads
  #     - ./app:/app/app
  #   depends_on:
  #     - postgres
  #     - neo4j
  #     - qdrant
  #     - redis
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # === Celery Worker ===
  worker:
    build: 
      context: .
      dockerfile: Dockerfile.celery
    container_name: kg_worker
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:1234@postgres:5432/kg_mvp
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_DIR=/app/uploads/raw
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
    # - ./backend:/app/backend  # Монтируем для разработки
    - ./uploads:/app/uploads
    depends_on:
      - postgres
      - neo4j
      - qdrant
      - redis
    command: celery -A backend.app.tasks.celery_app:celery_app worker --loglevel=info --concurrency=2
    restart: unless-stopped
  # === PostgreSQL ===
  postgres:
    image: postgres:15-alpine
    container_name: kg_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=kg_mvp
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # === Neo4j ===
  neo4j:
    image: neo4j:5.15-community
    container_name: kg_neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s  # Даем время на запуск
    restart: unless-stopped
   
  # === Qdrant ===
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: kg_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  # === Redis ===
  redis:
    image: redis:7-alpine
    container_name: kg_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  uploads_data:
  app:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  qdrant_data:
  redis_data: